version: 2.1


workflows:
  version: 2

  main_workflow:
    jobs:
      - check-version
      - Frontend:
          requires:
            - check-version
      - Backend-py27:
          requires:
            - check-version
      - Backend-py36:
          requires:
            - check-version
      - Dredd-py27:
          requires:
            - check-version
      - Dredd-py36:
          requires:
            - check-version


aliases:
  - &yarn_restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  - &yarn_save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
        - node_modules

  - &backend_setup
    working_directory: ~/Medusa/
    steps:
      - checkout
      - restore_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}
      - run:
          name: install
          command: |
            pip install --user --upgrade pip
            pip install --user --upgrade tox
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
      - run:
          name: test
          command: tox -v --recreate
      - save_cache:
          paths:
            - ~/.cache/pip
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}
      - store_test_results:
          path: reports

  - &dredd_setup
    working_directory: ~/Medusa/
    steps:
      - checkout
      - *yarn_restore_cache
      - run:
          name: install python deps
          command: |
            pip install --user --upgrade pip
            pip install --user dredd_hooks
            pip install --user 'PyYAML>=5.1'
            pip install --user six
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile --ignore-scripts
      - run:
          name: test
          command: yarn test-api
      - *yarn_save_cache
      - run:
          name: Dredd Hooks log
          command: /bin/cat ./dredd/hook.log
          when: on_fail
      - store_test_results:
          path: reports


jobs:
  check-version:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/Medusa/
    steps:
      - checkout
      - run: python .circleci/check_version.py

  Frontend:
    docker:
      - image: circleci/node:10.16.0
    environment:
      JEST_JUNIT_OUTPUT: ./reports/jest/results.xml
    working_directory: ~/Medusa/themes-default/slim
    steps:
      - checkout:
          path: ~/Medusa
      - *yarn_restore_cache
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile --ignore-scripts
      # - run:
      #     name: build-themes-check.sh
      #     command: |
      #       chmod +x ~/Medusa/.circleci/build-themes-check.sh
      #       ~/Medusa/.circleci/build-themes-check.sh
      - run: yarn lint --format junit --output-file ./reports/eslint/results.xml
      - run: yarn lint-css
      - run:
          name: Run tests
          command: yarn test --maxWorkers=2 --ci --reporters=default --reporters=jest-junit
      # - run:
      #     name: Upload test coverage
      #     command: yarn coverage
      - *yarn_save_cache
      - store_test_results:
          path: reports

  Backend-py27:
    docker:
      - image: circleci/python:2.7.13
    environment:
      TOXENV: py27
    <<: *backend_setup

  Backend-py36:
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36,lint
    <<: *backend_setup

  Dredd-py27:
    docker:
      - image: nikolaik/python-nodejs:python2.7-nodejs10
    <<: *dredd_setup

  Dredd-py36:
    docker:
      - image: nikolaik/python-nodejs:python3.6-nodejs10
    <<: *dredd_setup
