version: 2.1


workflows:
  version: 2

  main_workflow:
    jobs:
      - check-version
      - Frontend:
          requires:
            - check-version
      - Backend-py27:
          requires:
            - check-version
      - Backend-py36:
          requires:
            - check-version


aliases:
  - &yarn_restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  - &yarn_save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
        - node_modules

  - &pip_restore_cache
    restore_cache:
      key: pip-packages-v1-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}
  - &pip_save_cache
    save_cache:
      paths:
        - ~/.cache/pip
      key: pip-packages-v1-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}

  - &backend_install
    run:
      name: install
      command: |
        pip install --user --upgrade pip
        pip install --user --upgrade tox
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
  - &backend_test
    run:
      name: test
      command: tox -v --recreate


jobs:
  check-version:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/Medusa/
    steps:
      - checkout
      - run: python .circleci/check_version.py

  Frontend:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/Medusa/themes-default/slim
    steps:
      - checkout:
          path: ~/Medusa
      - *yarn_restore_cache
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile --ignore-scripts
      - run:
          name: build-themes-check.sh
          command: |
            chmod +x ~/Medusa/.circleci/build-themes-check.sh
            ~/Medusa/.circleci/build-themes-check.sh
      - run: yarn lint
      - run: yarn lint-css
      - run:
          name: Run tests
          command: yarn test --maxWorkers=2
      # - run:
      #     name: Upload test coverage
      #     command: yarn coverage
      - *yarn_save_cache

  Backend-py27:
    docker:
      - image: circleci/python:2.7.13
    environment:
      TOXENV: py27
    working_directory: ~/Medusa/
    steps:
      - checkout
      - *pip_restore_cache
      - *backend_install
      - *backend_test
      - *pip_save_cache

  Backend-py36:
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36,lint
    working_directory: ~/Medusa/
    steps:
      - checkout
      - *pip_restore_cache
      - *backend_install
      - *backend_test
      - *pip_save_cache
