version: 2.1
workflows:
  version: 2
  test:
    jobs:
      # TODO: "Check version" stage
      - Frontend
      # - Backend tests (py2.7)
aliases:
  - &yarn_restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  - &yarn_save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
  - &pip_restore_cache
    restore_cache:
      key: pip-packages-v1-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}
  - &pip_save_cache
    save_cache:
      paths:
        - ~/.cache/pip
      key: pip-packages-v1-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "requirements.txt" }}
jobs:
  Frontend:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/Medusa/themes-default/slim
    steps:
      - checkout:
          path: ~/Medusa
      - *yarn_restore_cache
      - run:
          name: yarn install
          command: yarn install --frozen-lockfile --ignore-scripts
      - run:
          name: build-themes-check.sh
          command: |
            chmod +x ~/Medusa/.circleci/build-themes-check.sh
            ~/Medusa/.circleci/build-themes-check.sh
      - run: yarn lint
      - run: yarn lint-css
      - run:
          name: Run tests
          command: yarn test --maxWorkers=2
      # - run:
      #     name: Upload test coverage
      #     command: yarn coverage
      - *yarn_save_cache
  # Backend tests (py2.7):
  #   docker:
  #     - image: circleci/python:2.7.14
  #   steps:
  #     - checkout
  #     - run: <command>
